name: Deploy dbt docs (Data Catalog) to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Prepare connection profile
        run: cp profiles.example.yml profiles.yml

      - name: Generate docs
        run: dbt docs generate
        env:
          DBT_ENV_SECRET_PASSWORD: ${{ secrets.DBT_ENV_SECRET_PASSWORD }}

      - name: Prepare Jekyll-compatible overview
        run: |
          # Convert dbt docs overview to Jekyll-compatible format
          sed -i '1i---\nlayout: default\ntitle: Overview\n---' macros/overview.md
          sed -i '/{% docs overview %}/d' macros/overview.md
          sed -i '/{% enddocs %}/d' macros/overview.md

      - name: Prepare site files
        run: |
          mkdir -p site
          cp target/index.html site/
          cp target/manifest.json site/
          cp target/catalog.json site/
          cp macros/overview.md site/README.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site