name: Deploy dbt docs (Data Catalog) to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install requirements
        run: pip install -r requirements.txt
          
      - name: Prepare connection profile
        run: cp profiles.example.yml profiles.yml

      - name: Generate docs
        run: dbt docs generate
        env:
          DBT_ENV_SECRET_PASSWORD: ${{ secrets.DBT_ENV_SECRET_PASSWORD }}

      - name: Prepare site files
        run: |
          mkdir -p site
          cp -r target/. site/
          touch site/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          enable_jekyll: false
          force_orphan: true
